apiVersion: apps/v1
kind: Deployment
metadata:
  name: laundrycompany
  labels:
    app: laundrycompany
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laundrycompany
  template:
    metadata:
      labels:
        app: laundrycompany
    spec:
      containers:
        - name: laundrycompany
          image: 936103362868.dkr.ecr.eu-central-1.amazonaws.com/laundrycompany:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: MAX_LAUNDRYCOUNT_PER_PERSON
              valueFrom:
                configMapKeyRef:
                  name: team01-config
                  key: max_laundrycount_per_person
            - name: UI_PROPERTIES_FILE_NAME
              valueFrom:
                configMapKeyRef:
                  name: team01-config
                  key: ui_properties_file_name
