apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 936103362868.dkr.ecr.eu-central-1.amazonaws.com/gateway:v1 #username을 fullname으로 수정해야함.
          ports:
            - containerPort: 8080
