server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: pickup
          uri: http://localhost:8081
          predicates:
            - Path=, 
        - id: pay
          uri: http://localhost:8082
          predicates:
            - Path=, 
        - id: laundrycompany
          uri: http://localhost:8083
          predicates:
            - Path=/**
        - id: message
          uri: http://localhost:8084
          predicates:
            - Path=,     
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pickup
          uri: http://pickup:8080
          predicates:
            - Path=/pickup/**, 
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/pay/**, 
        - id: laundrycompany
          uri: http://laundrycompany:8080
          predicates:
            - Path=/laundrycompany/**
        - id: message
          uri: http://message:8080
          predicates:
            - Path=/message/**    
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
